services:
  mysql:
    image: mysql:8.2.0
    container_name: ${APP_NAME}-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_PASSWORD: ${DB_ROOT_PASSWORD}
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --bind-address=0.0.0.0
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${MYSQL_ROOT_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    ports:
      - ${DB_EXPOSED_PORT}:3306
volumes:
  mysql_data:
    name: ${APP_NAME}-mysql_data

networks:
  app-network:
    name: ${APP_NAME}-network
    external: true