spring:
  application:
    name: TelegDash
  profiles:
    active:

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true

server:
  shutdown:
    grace-period: 30s