spring:
  mail:
    host:
    port:
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
    custom-name:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  main:
    allow-bean-definition-overriding: true
logging:
  level:
    org:
      springframework:
        security:
          OFF
api:
  telegdash:
  auth:
    username:
    password:
app:
  security:
    jwt:
      secret-key: c0182a0c93fdf659eb425445c099af10c66ce08fca923360bf67139abb1fb5a3
      expiration: 604800000 #86400000 # 1 day
      refresh-token:
        expiration: 604800000 # 7 days
    allowed:
      origin:
  sudo:
payment:
  paypal:
    client-id:
    secret:
    api:
      base-url:

#server:
#  servlet:
#    context-path: "/api/v1.0"
