package net.techbridges.telegdash.model.enums;

public enum Niche {
    TRADING,
    ECOMMERCE,
    BLOG,
    NEWS,
    CRYPTO,
    FINANCE,
    TECHNOLOGY,
    ENTERTAINMENT,
    SPORTS,
    HEALTH_AND_FITNESS,
    TRAVEL,
    FASHION,
    COOKING,
    PERSONAL_DEVELOPMENT,
    GAMING,
    MUSIC,
    EDUCATION,
    POLITICS,
    SOCIAL_MEDIA,
    BUSINESS,
    MARKETING,
    SCIENCE,
    BEAUTY,
    PETS,
    RELIGION,
    LIFESTYLE,
    BOOKS,
    MOTIVATION,
    PHOTOGRAPHY,
    LANGUAGE_LEARNING,
    DESIGN,
    CELEBRITIES,
    PARENTING,
    PODCASTS,
    TRADING_SIGNALS,
    LAW,
    MOVIES,
    WRITING,
    PRIVATE_CONTENT,
    SOFTWARE,
    UNDEFINED

    //todo, reduce this list
}
