#name: Build and Push Image
#
#on:
#  push:
#    branches:
#      - main
#    paths:
#      - 'src/**'
#      - 'Dockerfile'
#      - '.github/workflows/pipeline-build-api.yml'
#
#env:
#  REGISTRY: ghcr.io
#  IMAGE_NAME: telegdash
#  DOCKERFILE: Dockerfile
#  JAR_FILE_NAME: telegdash
#
#jobs:
#  build-and-push:
#    runs-on: ubuntu-latest
#    permissions:
#      contents: read
#      packages: write
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#
#      - name: Log in to GitHub Container Registry
#        uses: docker/login-action@v3
#        with:
#          registry: ${{ env.REGISTRY }}
#          username: ${{ github.actor }}
#          password: ${{ secrets.GITHUB_TOKEN }}
#
#      - name: Build and push Docker image
#        uses: docker/build-push-action@v5
#        with:
#          context: .
#          file: ${{ env.DOCKERFILE }}
#          build-args: |
#            JAR_FILE_NAME=${{env.JAR_FILE_NAME}}
#          push: true
#          tags: |
#            ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:1.0.0
#            ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ github.sha }}